Fix 'React is used before defined' in TS files
codesandbox/codesandbox-client pull request #5000
Opened 2020-10-12 18:50 UTC by CompuIves

For TS files there needs to be a different check, based on https://stackoverflow.com/questions/63818415/react-was-used-before-it-was-defined.

2020-10-12 18:56 UTC, lbogdan commented
<!-- drone -->
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5000/commits/d0c534a44ca040b36693a444e901a7e2a563ecbe is at https://pr5000.build.csb.dev/s/new.

2020-10-13 09:32 UTC, christianalfoni requested changes
Just for consistency 😄

2020-10-13 09:32 UTC, christianalfoni commented on packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
> +    '@typescript-eslint/no-use-before-define': ['error'],
```suggestion
    '@typescript-eslint/no-use-before-define': 'error',
```

2020-10-13 09:48 UTC, CompuIves commented
Ah good one!

2020-10-13 10:19 UTC, christianalfoni approved these changes
Great! 👍

2020-10-13 10:34 UTC, merged