fix text truncate
codesandbox/codesandbox-client pull request #5409
Opened 2021-01-27 15:30 UTC by alexnm

Dashboard - List View
- "Always-On" column replaced with a small green circle overlapping the sandbox image
- Sandbox name column wider
- Text overflow only when there's no room, removed fixed width

Sandbox templates list
- Text overflow only when there's no room, removed fixed width
- `title` attribute added so the full name is visible on hover (via browser default tooltip)

Breakpoints
- Found a 3px difference between sidebar toggle (770px) and main content going full width (767px)

2021-01-27 15:32 UTC, alexnm commented on packages/app/src/app/pages/Dashboard/index.tsx
> -                    as="aside"
this was creating two `aside` tags nested, <Sidebar> is already adding the content as an `aside`

2021-01-27 15:39 UTC, lbogdan commented
<!-- drone -->
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5409/commits/122bc675d8ba6f7c2abce4c1d5bafb57215ee9d8 is at https://pr5409.build.csb.dev/s/new.

2021-01-27 18:36 UTC, SaraVieira approved these changes
Looks great! Good work!

2021-01-28 12:00 UTC, DannyRuchtie requested changes
Hi Alex,

I discovered that we are using something similar in the activity bar. 
But I don't know if that already is a component that you can reuse 

The design is slightly different (sorry I forgot about this one). It is 10*10 plus a border of 2px with the background color as the border color.


<img width="209" alt="Screenshot 2021-01-28 at 12 54 26" src="https://user-images.githubusercontent.com/46239581/106135844-bf5d7c00-6168-11eb-9a92-7a2cb073b013.png">



There also is an issue with Safari. what else :( 

<img width="168" alt="Screenshot 2021-01-28 at 12 56 46" src="https://user-images.githubusercontent.com/46239581/106135780-ad7bd900-6168-11eb-9d21-238f48c86e5f.png">

2021-01-28 16:12 UTC, alexnm commented
made the bubble 12x12 and fixed the overflow cut

2021-01-29 10:36 UTC, DannyRuchtie approved these changes

2021-01-29 11:08 UTC, merged