Fix printer to print optional chains
codesandbox/codesandbox-client pull request #6170
Opened 2021-09-29 09:44 UTC by CompuIves

2021-09-29 09:53 UTC, lbogdan commented
<!-- drone -->
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6170/commits/334e250e61d4b56ebc9854c1edfaafa887fbad75 is at https://pr6170.build.csb.dev/s/new.

2021-09-29 09:53 UTC, DeMoorJasper approved these changes

2021-09-29 10:03 UTC, DeMoorJasper requested changes
Apparently breaks some other sandboxes...

2021-10-01 07:28 UTC, DeMoorJasper commented
Closing in favor of #6173

2021-10-01 07:28 UTC, closed without merging