style(Header): facelift, standardization and menu changes.
codesandbox/codesandbox-client pull request #7324
Opened 2023-01-17 18:34 UTC by marcovincit

This is a facelift PR, there are only visual design changes.

- User menu:
   - Goes to the left side with logo, standardizing dashboard and editor menu.
   - Add a menu link to go to website.
   - Add a menu link to go to new discover.
   
- Button component: 
   - Standardization of styles that are currently incorrect (sizes, border-radius).
   - Create ghost variant.
   
- Search:
   - Fixed alignment.
   - Visual changes.

# General:

### Current visual
![current-header](https://user-images.githubusercontent.com/2926010/212976391-a6c1d0a6-ae74-406f-b53c-d11c580db20b.jpg)

### New visual
![new-header](https://user-images.githubusercontent.com/2926010/212976407-a0e61277-25fd-48dd-97f4-65327d9d5474.jpg)

# User menu:

| Current      | New |
| ----------- | ----------- |
| ![current-header](https://user-images.githubusercontent.com/2926010/212978431-f3213976-bb5a-42c2-91c6-f929492d7b48.jpg)  | ![new-header](https://user-images.githubusercontent.com/2926010/212978505-01268156-6972-4e82-80d0-ce9d623ae266.jpg)   |

2023-01-17 22:01 UTC, olarclara commented on packages/app/src/app/components/dashboard/InputSelect.tsx
> +
```suggestion

```

2023-01-17 22:02 UTC, olarclara approved these changes

2023-01-18 15:08 UTC, lenasmayor approved these changes

2023-01-19 16:26 UTC, olarclara commented on packages/components/src/components/Button/index.tsx
> +    },
Does the following work?

```suggestion
    ':hover:not(:disabled), :focus:not(:disabled)'': {
      color: 'foreground',
      backgroundColor: '#E5E5E51A',
    },
```

2023-01-19 16:28 UTC, olarclara commented on packages/components/src/components/Button/index.tsx
>    transitionDuration: theme => theme.speeds[2],
Does the duration (`300ms`) defined in line 114 gets overridden by the transition duration (`theme.speeds[2] = 100ms`) set in line 116?

2023-01-19 16:31 UTC, olarclara commented on packages/app/src/app/components/Notifications/index.tsx
> +export const Notifications = ({ dashboard }: any) => {
```suggestion
export const Notifications = ({ dashboard }: { dashboard?: boolean }) => {
```

2023-01-19 16:43 UTC, olarclara requested changes
Can you repro this issue? Seems that only the create button and the search render at first causing the screen to glitch.

https://user-images.githubusercontent.com/24959348/213503828-4b02be2d-b03e-414a-a6e3-e6b285405041.mov

2023-01-20 17:24 UTC, olarclara approved these changes
Looks great!

2023-01-20 17:43 UTC, merged