fix(dashboard/settings): user invite hangs
codesandbox/codesandbox-client pull request #7382
Opened 2023-02-01 04:26 UTC by olarclara

## What kind of change does this PR introduce?

Replaces the alert modal with a banner if adding another editor will increase the subscription charges.

## What is the current behavior?

In the first render, the modal does not appear and leaves the user hanging. This is hard to reproduce because it goes away after a refresh.

## What is the new behavior?

I couldn't find a way to fix it (but thinking now, maybe forcing a re-render inside the component might help), so I removed the confirmation step and added a banner informing about the charges that will occur when adding a new editor.

![cyt2tt-3000 preview csb app_dashboard_settings_workspace=aa86c532-6129-4c06-a8cc-979bfcb72424](https://user-images.githubusercontent.com/24959348/215945917-40d9e249-c912-429a-b8e6-1f0efd0c5473.png)

I also fixed the form input to prevent performing any action if it was empty.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Go to a pro team where you are an admin
2. See the banner
3. Inviting new members performs the action w/o any steps in-between
4. Copying the invite link performs the action w/o any steps in-between

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table

2023-02-01 08:50 UTC, tristandubbeld approved these changes
The behaviour of inviting others is really curious, it seems to work very differently in multiple scenarios. Sometimes the modal doesn't show up, sometimes it does. Sometimes it invites a user without confirming the dialog too. I think we need to spend some time to look into the deeper layers when we can. This PR looks good to me though!

2023-02-01 08:54 UTC, tristandubbeld commented on packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/AdditionalEditorsCharges.tsx
> +      (activeTeam === personalWorkspaceId ? 'pro' : 'teamPro') ?? 'pro';
Isn't it always `teamPro`? Since personal workspaces can't invite new users.

2023-02-01 12:44 UTC, tristandubbeld requested changes
Actually! I just tried to reproduce this a few times on production and it seems that removing the buggy code that closed the "create new" modal was also closing this one. Can you confirm this?

2023-02-02 02:25 UTC, olarclara commented
@tristandubbeld thank you for catching this! I'll close and keep an eye out if the issue happens again.

2023-02-02 02:25 UTC, closed without merging