feat: update upgrade page
codesandbox/codesandbox-client pull request #8264
Opened 2024-01-11 13:45 UTC by danilowoz

2024-01-11 16:01 UTC, necoline requested changes

2024-01-11 16:01 UTC, necoline commented on packages/app/src/app/constants.ts
>    credits: 6400,
this should be 4000

2024-01-11 16:01 UTC, necoline commented on packages/app/src/app/constants.ts
>    credits: 22400,
this should be 24000

2024-01-11 16:31 UTC, alexnm approved these changes

2024-01-12 09:28 UTC, necoline approved these changes

2024-01-12 09:28 UTC, merged